### ISSUE TITLE
PR close workflow not triggered for Auto Close of PR

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1568] opened 2023-11-02 21:57 UTC
https://github.com/bcgov/quickstart-openshift/pull/1555

**Comment by DerekRoberts** [comment] 2023-11-03 03:13
Looks like Renovate is renaming PRs and closing in the same step when there's an autoclose.  Thankfully this only seems to be an issue when Renovate users are changed.  I have not been able to figure out how to reproduce this otherwise.  Closing, but will revisit as necessary.

**Closed by DerekRoberts** 2023-11-03 03:13 UTC
Labels: bug
